# Generated by Django 4.1.2 on 2022-11-14 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=50)),
                ('Tage', models.CharField(max_length=50)),
                ('TPhno', models.BigIntegerField()),
                ('Temail', models.EmailField(max_length=50)),
                ('Tcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainerapp.city')),
                ('Tcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainerapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Batch_Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchNo', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Tr_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainerapp.course')),
                ('Tr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainerapp.trainer_reg')),
            ],
        ),
    ]
