# Generated by Django 4.1.2 on 2022-11-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_reg',
            name='Tpassword',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
